In [2]:
#code cell for running BFS

from collections import deque
import numpy as np
def bfs ():
    #define start and goal nodes
    start = np.array([[8 , 6 , 7],
                  [2 , 5 , 4],
                  [3 , 0 , 1]])
    goal = np.array([[1 , 2 , 3],
                     [4  , 5 ,6],
                     [7 , 8 , 0]])
    #Defin required variables for further creating text files
    start_tup = tuple(start.flatten())
    index = 0
    index_up = 0
    dic = {start_tup : index}
    explored_states = [start]
    nodes_info = [[0 , -1 , start_tup]]
    visited = set()
    #Define the queue
    queue = deque([(start, [start])])
    reached = 0
    p_node_index = 0
    node_index = 0
    no_solution = 0
    #start the algo
    while reached == 0 :
        if (len(queue) == 0) :
            no_solution = 1
            print('no solution')
            break
        current_state , path = queue.popleft()
        moves = []
        zero_position = np.argwhere(current_state == 0)[0]
        row, col = zero_position
        possible_moves = [(row , col-1), (row + 1, col), (row, col + 1), (row - 1, col)]
        # Carry out necessary checks
        if tuple(current_state.flatten()) not in visited:
                current_state_tup = tuple(current_state.flatten())
                visited.add(current_state_tup)
                p_index = dic[current_state_tup]
                for move in possible_moves:
                    new_row, new_col = move
                    if 0 <= new_row < 3 and 0 <= new_col < 3:
                        index_up += 1
                        new_state = current_state.copy()
                        new_state[row, col], new_state[new_row, new_col] = new_state[new_row, new_col], new_state[row, col]
                        moves.append(new_state)
                        explored_states.append(new_state)
                        nodes_info.append([index_up , p_index , tuple(new_state.flatten())])
                        dic[tuple(new_state.flatten())] = index_up
                for move in moves:
                    queue.append((move, path + [move]))
                    if (np.array_equal(move , goal)):
                        print("Goal state reached")
                        path.append(goal)
                        reached = 1
                        break
    return path , nodes_info , no_solution, explored_states               

path , nodes_info, no_solution, explored_states = bfs()
if (no_solution == 1):
    print('cannot print path')
else:
    for step in path:
        print(step)

Goal state reached
[[8 6 7]
 [2 5 4]
 [3 0 1]]
[[8 6 7]
 [2 5 4]
 [0 3 1]]
[[8 6 7]
 [0 5 4]
 [2 3 1]]
[[8 6 7]
 [5 0 4]
 [2 3 1]]
[[8 6 7]
 [5 3 4]
 [2 0 1]]
[[8 6 7]
 [5 3 4]
 [2 1 0]]
[[8 6 7]
 [5 3 0]
 [2 1 4]]
[[8 6 7]
 [5 0 3]
 [2 1 4]]
[[8 0 7]
 [5 6 3]
 [2 1 4]]
[[8 7 0]
 [5 6 3]
 [2 1 4]]
[[8 7 3]
 [5 6 0]
 [2 1 4]]
[[8 7 3]
 [5 0 6]
 [2 1 4]]
[[8 7 3]
 [0 5 6]
 [2 1 4]]
[[8 7 3]
 [2 5 6]
 [0 1 4]]
[[8 7 3]
 [2 5 6]
 [1 0 4]]
[[8 7 3]
 [2 5 6]
 [1 4 0]]
[[8 7 3]
 [2 5 0]
 [1 4 6]]
[[8 7 3]
 [2 0 5]
 [1 4 6]]
[[8 0 3]
 [2 7 5]
 [1 4 6]]
[[0 8 3]
 [2 7 5]
 [1 4 6]]
[[2 8 3]
 [0 7 5]
 [1 4 6]]
[[2 8 3]
 [1 7 5]
 [0 4 6]]
[[2 8 3]
 [1 7 5]
 [4 0 6]]
[[2 8 3]
 [1 0 5]
 [4 7 6]]
[[2 0 3]
 [1 8 5]
 [4 7 6]]
[[0 2 3]
 [1 8 5]
 [4 7 6]]
[[1 2 3]
 [0 8 5]
 [4 7 6]]
[[1 2 3]
 [4 8 5]
 [0 7 6]]
[[1 2 3]
 [4 8 5]
 [7 0 6]]
[[1 2 3]
 [4 0 5]
 [7 8 6]]
[[1 2 3]
 [4 5 0]
 [7 8 6]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [3]:
#code cell for creating NodesInfo.txt

file_path = r"C:\Users\Navdeep\Documents\NodesInfo.txt"
column_names = ['node_index', 'parent_node_index', 'node']
with open(file_path, 'w') as file:
    file.write(' '.join(column_names) + '\n')
    for sublist in nodes_info:
        row_data = ' '.join(map(str, sublist))
        file.write(row_data + '\n')


In [4]:
#code cell for creating Nodes.txt

file_path = r'C:\Users\Navdeep\Documents\Nodes.txt'
with open(file_path, 'w') as file:
    for array in explored_states:
        flattened_array = array.flatten() 
        file.write(' '.join(map(str, flattened_array)) + '\n')

In [5]:
#code cell for creating nodePath.txt

file_path = r"C:\Users\Navdeep\Documents\nodePath.txt"
with open(file_path, 'w') as file:
    for node in path :
            col1 = node[: , 0]
            col2 = node[: , 1]
            col3 = node[: , 2]
            tup1 = tuple(col1)
            tup2 = tuple(col2)
            tup3 = tuple(col3)
            tup = tup1 + tup2 + tup3
            file.write(' '.join(map(str, tup)) + '\n')
            print(tup)

(8, 2, 3, 6, 5, 0, 7, 4, 1)
(8, 2, 0, 6, 5, 3, 7, 4, 1)
(8, 0, 2, 6, 5, 3, 7, 4, 1)
(8, 5, 2, 6, 0, 3, 7, 4, 1)
(8, 5, 2, 6, 3, 0, 7, 4, 1)
(8, 5, 2, 6, 3, 1, 7, 4, 0)
(8, 5, 2, 6, 3, 1, 7, 0, 4)
(8, 5, 2, 6, 0, 1, 7, 3, 4)
(8, 5, 2, 0, 6, 1, 7, 3, 4)
(8, 5, 2, 7, 6, 1, 0, 3, 4)
(8, 5, 2, 7, 6, 1, 3, 0, 4)
(8, 5, 2, 7, 0, 1, 3, 6, 4)
(8, 0, 2, 7, 5, 1, 3, 6, 4)
(8, 2, 0, 7, 5, 1, 3, 6, 4)
(8, 2, 1, 7, 5, 0, 3, 6, 4)
(8, 2, 1, 7, 5, 4, 3, 6, 0)
(8, 2, 1, 7, 5, 4, 3, 0, 6)
(8, 2, 1, 7, 0, 4, 3, 5, 6)
(8, 2, 1, 0, 7, 4, 3, 5, 6)
(0, 2, 1, 8, 7, 4, 3, 5, 6)
(2, 0, 1, 8, 7, 4, 3, 5, 6)
(2, 1, 0, 8, 7, 4, 3, 5, 6)
(2, 1, 4, 8, 7, 0, 3, 5, 6)
(2, 1, 4, 8, 0, 7, 3, 5, 6)
(2, 1, 4, 0, 8, 7, 3, 5, 6)
(0, 1, 4, 2, 8, 7, 3, 5, 6)
(1, 0, 4, 2, 8, 7, 3, 5, 6)
(1, 4, 0, 2, 8, 7, 3, 5, 6)
(1, 4, 7, 2, 8, 0, 3, 5, 6)
(1, 4, 7, 2, 0, 8, 3, 5, 6)
(1, 4, 7, 2, 5, 8, 3, 0, 6)
(1, 4, 7, 2, 5, 8, 3, 6, 0)


In [7]:
 #code for visualization

import pygame
import time
import numpy as np
# open the file for reading
with open(r"C:\Users\Navdeep\Documents\nodePath.txt", 'r') as f:
   # read the content of the file
   content = f.read()
# split the content by blank line to get a list of matrix strings
strings = content.strip().split('\n')
# create a list of 3x3 matrices from the matrix strings
track = []
for string in strings:
   values = list(map(int, string.split()))
   state = np.array(values).reshape(3, 3)
#     print(state)
   track.append(state.T)
# track.reverse()
# initialize pygame
pygame.init()
# set the size of the game window
window_size = (300, 300)
screen = pygame.display.set_mode(window_size)
# set the title of the game window
pygame.display.set_caption("8 Puzzle Game")
# define colors
white = (255, 255, 255)
black = (0, 0, 0)
grey = (128, 128, 128)
# set the font
font = pygame.font.SysFont('Arial', 30)
# define the size of the puzzle grid
grid_size = 3
cell_size = 100
# define the position of the puzzle numbers
puzzle_positions = [(i % grid_size, i // grid_size) for i in range(grid_size ** 2)]
# define the position of the empty cell
empty_position = puzzle_positions[-1]
# define a function to draw the puzzle board
def draw_board():
   for i in range(grid_size):
       for j in range(grid_size):
           x = j * cell_size
           y = i * cell_size
           index = puzzle_positions.index((j, i))
           number = puzzle_numbers[index]
           if number != 0:
               pygame.draw.rect(screen, white, (x, y, cell_size, cell_size))
               text = font.render(str(number), True, black)
               text_rect = text.get_rect(center=(x+cell_size/2, y+cell_size/2))
               screen.blit(text, text_rect)
           else:
               pygame.draw.rect(screen, grey, (x, y, cell_size, cell_size))
# define the main game loop
running = True
i=0
while running  :
   # handle events
   for event in pygame.event.get():
       if event.type == pygame.QUIT:
           running = False
   # clear the screen
   screen.fill(grey)
#     update position
   if i<len(track):
       puzzle_numbers=track[i].flatten()
       i+=1
   # draw the puzzle board
   draw_board()
   time.sleep(1)
   # update the screen
   pygame.display.update()
# quit pygame
pygame.quit()